### ISSUE TITLE
Random Python error (ValueError in run.py)

### ISSUE THREAD

**Issue by sy6sy2** [YunoHost/yunorunner#29]
Hi,

When I use the bot with the `!testme` trigger I randomly get a Python error during the CI test:

```
Job error on:
Traceback (most recent call last):
  File "./run.py", line 431, in run_job
    }, ["jobs", f"job-{job.id}", f"app-jobs-{job.url_or_path}"])
  File "./run.py", line 491, in broadcast
    ws_list.remove(to_remove)
ValueError: list.remove(x): x not in list
```

You will find a real example here: https://ci-apps-dev.yunohost.org/ci/job/3492

**Comment by alexAubin** [comment]
Fixed some time ago if i recall correctly
